// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6dY9Taa38MTCXj6e-9KDOON1ABghi7c',
    appId: '1:156884977245:web:1d189be1be91668270efb4',
    messagingSenderId: '156884977245',
    projectId: 'final-project-cins467-28435',
    authDomain: 'final-project-cins467-28435.firebaseapp.com',
    storageBucket: 'final-project-cins467-28435.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCoON-6d1YiIZ5zADe7gsMtrh8WRwF9s',
    appId: '1:156884977245:android:c95bbcaff2ad980970efb4',
    messagingSenderId: '156884977245',
    projectId: 'final-project-cins467-28435',
    storageBucket: 'final-project-cins467-28435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmKnlJPzNJfPPSf57Yf2SjnHPMiUZBOco',
    appId: '1:156884977245:ios:d98372509a522ef470efb4',
    messagingSenderId: '156884977245',
    projectId: 'final-project-cins467-28435',
    storageBucket: 'final-project-cins467-28435.firebasestorage.app',
    iosBundleId: 'com.example.cleanstreak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmKnlJPzNJfPPSf57Yf2SjnHPMiUZBOco',
    appId: '1:156884977245:ios:d98372509a522ef470efb4',
    messagingSenderId: '156884977245',
    projectId: 'final-project-cins467-28435',
    storageBucket: 'final-project-cins467-28435.firebasestorage.app',
    iosBundleId: 'com.example.cleanstreak',
  );
}
